version: '3.8'

services:
  neo4j:
    image: neo4j:5.19.0-community
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"   # HTTP 浏览器访问
      - "7687:7687"   # Bolt 协议访问
    environment:
      - NEO4J_AUTH=neo4j/password123  # 初始用户名密码
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512m
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
